# 1.Find dot product of 2 vectors using dot. a=i+2j-k,b=2i-k.

In [1]:
import numpy as np
a = np.array([1, 2, -1])
b = np.array([2, 0, -1])

arr= np.dot(a, b)
print(arr)

3


# 2.Use vectorization factor to add two array of size 3x4.

In [6]:
import numpy as np
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

arr1 = np.array([[13, 14, 15, 16],[17, 18, 19, 20],[21, 22, 23, 24]])

arr2 = arr + arr1

print(arr)
print(arr1)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[14 16 18 20]
 [22 24 26 28]
 [30 32 34 36]]


# 3.Use vectorization to divide a 3D array by 5.

In [14]:
import numpy as np
arr = np.arange(1, 25).reshape(2, 3, 4)
result = arr/ 5

print(arr)
print()
print(result)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

[[[0.2 0.4 0.6 0.8]
  [1.  1.2 1.4 1.6]
  [1.8 2.  2.2 2.4]]

 [[2.6 2.8 3.  3.2]
  [3.4 3.6 3.8 4. ]
  [4.2 4.4 4.6 4.8]]]


# 4.WAP to input array and find min element.

In [12]:
import numpy as np
arr_str = input("Enter the array elements:")
arr = np.array(list(map(int, arr_str.split())))
min_element = np.min(arr)

print("Minimum element:", min_element)

Enter the array elements:5 8 9 7 2 4 1
Minimum element: 1


# 5.find cross product of following vector.(a)=3i-4j+2k,(b)=i-2j

In [15]:
import numpy as np
a = np.array([3, -4, 2])
b = np.array([1, -2, 0])
c = np.cross(a, b)

print(c)

[ 4  2 -2]


# 6.find cross product of following vector.(a)=2i-3j-3k,(b)=4i-2j+k.

In [16]:
import numpy as np
a = np.array([2, -3, 3])
b = np.array([4, -2, 1])
c = np.cross(a, b)

print(c)

[ 3 10  8]
