# 1. Create a 2D array of 3x5 using any number with (array function).


In [1]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10],[11, 12, 13, 14, 15]])

print(arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


# 2. Create array of first 20 whole number using arange.

In [2]:
import numpy as np
wn = np.arange(1, 21)

print(wn)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


# 3.Use linspace function to get 12 linerly spaced value between 10 and 50 all values should be in integers.

In [4]:
import numpy as np
arr=np.linspace(10,50,12,dtype='int')
print(arr)

[10 13 17 20 24 28 31 35 39 42 46 50]


# 4.Create a 4Dim array each must contain 2 3 dim array each 3D array contain    4 two dim array of 3X4 they all must be filled  the number 5 

In [9]:
import numpy as np
arr=np.full((4,3,2,3),5)
print(arr)

[[[[5 5 5]
   [5 5 5]]

  [[5 5 5]
   [5 5 5]]

  [[5 5 5]
   [5 5 5]]]


 [[[5 5 5]
   [5 5 5]]

  [[5 5 5]
   [5 5 5]]

  [[5 5 5]
   [5 5 5]]]


 [[[5 5 5]
   [5 5 5]]

  [[5 5 5]
   [5 5 5]]

  [[5 5 5]
   [5 5 5]]]


 [[[5 5 5]
   [5 5 5]]

  [[5 5 5]
   [5 5 5]]

  [[5 5 5]
   [5 5 5]]]]


# 5.Create an identity matrix of 5x5 with complex data type.

In [22]:
import numpy as np
matrix = np.identity(5, dtype=complex)
print(matrix)

[[1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j]]


# 6. Create an identity matrix using eye function we k=2 and datatype must be in int.

In [25]:
import numpy as np
matrix = np.eye(5, k=2, dtype=int)
print(matrix)

[[0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]]


# 7.write code to extract k=-1 diagonal from 2D matric array.

In [26]:
import numpy as np 
arr=np.array([[10,40,50,60],[20,40,60,30],[10,30,40,60]])
arr2=np.diag(arr,-1)
print(arr)
print(arr2)

[[10 40 50 60]
 [20 40 60 30]
 [10 30 40 60]]
[20 30]


# 8.Create an array 3x4 using empty function.

In [32]:
import numpy as np
empty_array = np.empty((3, 4))
print(empty_array)

[[1.0609979e-313 1.0609979e-313 1.0609979e-313 1.0609979e-313]
 [1.0609979e-313 1.0609979e-313 1.0609979e-313 1.0609979e-313]
 [1.0609979e-313 1.0609979e-313 1.0609979e-313 1.0609979e-313]]


# 9.Create 2D array 3x4using random number from 10 to 20(20 is inclusive)

In [33]:
import numpy as np
random_array = np.random.randint(10, 21, size=(3, 4))
print(random_array)

[[20 19 15 19]
 [13 14 17 20]
 [20 16 18 20]]


# 10.Create a 3D array of random number from 0 to 100 size is 5x6 and there must be 4 2D array.

In [34]:
import numpy as pd
arr = np.random.randint(0, 101, size=(4, 5, 6))
print(arr)

[[[ 92  96  34  81  20  87]
  [ 42  34  24  63  68  80]
  [ 94  30  66  10  20  41]
  [ 36  70  10  35  31  54]
  [ 50  31  94  99  81  52]]

 [[ 92  97  10  48  94  80]
  [  2  75  78  44   5  95]
  [ 10  11  10  71  46  30]
  [ 54  59  77  87   6  16]
  [ 47  74  64  96  45  77]]

 [[100  81  93  14  74  83]
  [ 71  26 100  37   3  51]
  [  8  25  14  35  45  98]
  [ 33  12   8   6  75  12]
  [ 72   9  76   4   8  55]]

 [[ 74  11  36  88  68  10]
  [ 88  16  64  18  75  87]
  [ 13  14  63  69  84  42]
  [ 64   3  92  83  21  83]
  [ 46  90   5  38   3  88]]]
