# 1.Create a 2D array of 3x4 from number 12 to 24 and fetch. (a)=16, (b)=19, (c)=14.

In [4]:
import numpy as np
arr = np.arange(12, 24).reshape(3, 4)

a = arr[1, 0] 
b = arr[1, 3]
c = arr[0, 2] 

print(arr)

print(a)
print(b)
print(c)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
16
19
14


# 2. Create a 3D array for first 24 whole number of size 2x3x4 and fetch . (a)=16,(b)=4,(c)=0.

In [7]:
import numpy as np
arr= np.arange(24).reshape(2, 3, 4)

a = arr[1, 1, 0]  
b = arr[0, 1, 0]  
c = arr[0, 0, 0] 

print(arr)

print(a)
print(b)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
16
4
0


# 3.Create table of 5 and fetch all elements divisble by using condition based on indexing.

In [8]:
import numpy as np
arr = np.arange(1, 21) * 5
arr1 = arr[arr % 4 == 0]

print(arr)
print(arr1)

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]
[ 20  40  60  80 100]


# 4.Out of first 20 natural number find all number greater than 5 but less than 12.

In [9]:
import numpy as np
arr = np.arange(1, 21)

arr1 = arr[( arr> 5) & (arr < 12)]

print(arr)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 6  7  8  9 10 11]


# 5.Make an array of table of 5 and fetch all number which all divible by 3 and are also divisible by 4.

In [10]:
import numpy as np
arr= np.arange(1, 21) * 5

arr1= arr[(arr % 3 == 0) & (arr % 4 == 0)]

print(arr)
print(arr1)

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]
[60]


In [ ]:
#6.Create any 3D array and use nditer toget its element one by one.

In [12]:
import numpy as np

array = np.arange(24).reshape(2, 3, 4)

# Iterate over the elements of the 3D array using nditer
it = np.nditer(array, flags=['multi_index'])

while not it.finished:
    print("Element at index {}: {}".format(it.multi_index, it[0]))
    it.iternext()


Element at index (0, 0, 0): 0
Element at index (0, 0, 1): 1
Element at index (0, 0, 2): 2
Element at index (0, 0, 3): 3
Element at index (0, 1, 0): 4
Element at index (0, 1, 1): 5
Element at index (0, 1, 2): 6
Element at index (0, 1, 3): 7
Element at index (0, 2, 0): 8
Element at index (0, 2, 1): 9
Element at index (0, 2, 2): 10
Element at index (0, 2, 3): 11
Element at index (1, 0, 0): 12
Element at index (1, 0, 1): 13
Element at index (1, 0, 2): 14
Element at index (1, 0, 3): 15
Element at index (1, 1, 0): 16
Element at index (1, 1, 1): 17
Element at index (1, 1, 2): 18
Element at index (1, 1, 3): 19
Element at index (1, 2, 0): 20
Element at index (1, 2, 1): 21
Element at index (1, 2, 2): 22
Element at index (1, 2, 3): 23


# 7.Create a 3D array of number from 1 to 24 of size 4x3 and fetch element noe by one using ndenumerate.

In [19]:
import numpy as np
array= np.arange(1, 25).reshape(2,4,3)

# Fetch elements one by one using ndenumerate
for index, value in np.ndenumerate(array):
    print("Index:", index, "Value:", value)

Index: (0, 0, 0) Value: 1
Index: (0, 0, 1) Value: 2
Index: (0, 0, 2) Value: 3
Index: (0, 1, 0) Value: 4
Index: (0, 1, 1) Value: 5
Index: (0, 1, 2) Value: 6
Index: (0, 2, 0) Value: 7
Index: (0, 2, 1) Value: 8
Index: (0, 2, 2) Value: 9
Index: (0, 3, 0) Value: 10
Index: (0, 3, 1) Value: 11
Index: (0, 3, 2) Value: 12
Index: (1, 0, 0) Value: 13
Index: (1, 0, 1) Value: 14
Index: (1, 0, 2) Value: 15
Index: (1, 1, 0) Value: 16
Index: (1, 1, 1) Value: 17
Index: (1, 1, 2) Value: 18
Index: (1, 2, 0) Value: 19
Index: (1, 2, 1) Value: 20
Index: (1, 2, 2) Value: 21
Index: (1, 3, 0) Value: 22
Index: (1, 3, 1) Value: 23
Index: (1, 3, 2) Value: 24
