# 1.Guess out of a+b. (a)=np.array([[10],[20],[30]]) (b)=([1,2,3])

In [1]:
import numpy as np

a = np.array([[10], [20], [30]])
b = np.array([[1], [2], [3]])
c = a + b

print(c)

[[11]
 [22]
 [33]]


# 2.Guess out of a%b. (a)= np.array([[10,20], [30,40], [50,60]]) (b)= np.array([5])

In [2]:
import numpy as np
a = np.array([[10, 20], [30, 40], [50, 60]])
b = np.array([5])
c = a % b

print(c)

[[0 0]
 [0 0]
 [0 0]]


# 3.Guess output of a*b.(a)= np.array([[10,20,30], [40,50,60]) (b)= np.array([5,10])

In [13]:
import numpy as np
a = np.array([[10, 20, 30], [40, 50, 60]])
b = np.array([10])
c = a*b

print(c)

[[100 200 300]
 [400 500 600]]


# 4.Create table of 5 using arange and convert it into 5x2 array using reshape.

In [20]:
import numpy as np
a = np.arange(5, 51, 5)
b = a.reshape(5, 2)

print(a)
print()
print(b)

[ 5 10 15 20 25 30 35 40 45 50]

[[ 5 10]
 [15 20]
 [25 30]
 [35 40]
 [45 50]]


# 5. Resize an array of number 1 to 12 into 5x6 array.number must get repeated.

In [21]:
import numpy as np
a = np.arange(1, 13)
b= np.resize(a, (5, 6))

print(a)
print()
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [ 1  2  3  4  5  6]]


# 6. Resize a 1D array of table 7 into 4x5 array.Extra place contain must be 0.

In [23]:
import numpy as np
a=np.arange(7,71,7)
b=np.resize(a(4,5))

print(a)

[[ 7 14 21 28 35]
 [42 49 56 63 70]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]
