# 1.Create a 3D array of number 1 to 24 of size 2x4x3 and flatten it.

In [2]:
import numpy as np
arr= np.arange(1, 25).reshape(2, 4, 3)

# Flatten the 3D array
arr1 = arr.flatten()


print(arr)
print()
print(arr1)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


# 2.Demonstrate the difference between flatten and ravel using a suitable example.

In [4]:
import numpy as np
# Create a 2D array
arr = np.array([[1, 2, 3],[4, 5, 6]])
arr1 = arr.flatten()
arr1[0] = 100 
arr3 = arr.ravel()
arr3[0] = 200  

print("Original 2D array:")
print(arr)

print("\nFlattened array:")
print(arr1)

print("\nRaveled array:")
print(arr3)

Original 2D array:
[[200   2   3]
 [  4   5   6]]

Flattened array:
[100   2   3   4   5   6]

Raveled array:
[200   2   3   4   5   6]


# 3.Create a 2D array and find its transpose.

In [5]:
import numpy as np
arr = np.array([[1, 2, 3],[4, 5, 6]])

arr1 = np.transpose(arr)

print("Original 2D array:")
print(arr)

print("\nTranspose of the array:")
print(arr1)

Original 2D array:
[[1 2 3]
 [4 5 6]]

Transpose of the array:
[[1 4]
 [2 5]
 [3 6]]


# 4.Create a 3D array and transpose it on axes(2,0,1).

In [6]:
import numpy as np
arr = np.arange(1,25).reshape(2,3,4)
arr1=np.transpose(arr,axes=(2,0,1)) 

print(arr)
print()
print(arr1)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

[[[ 1  5  9]
  [13 17 21]]

 [[ 2  6 10]
  [14 18 22]]

 [[ 3  7 11]
  [15 19 23]]

 [[ 4  8 12]
  [16 20 24]]]


# 5.Create a 4D array and use swapaxes to swap 2 and 4 axes.

In [7]:
import numpy as np
arr= np.array([[[[1, 2], [3, 4]],[[5, 6], [7, 8]]],[[[9, 10], [11, 12]],[[13, 14],[15, 16]]]])

arr1 = np.swapaxes(arr, 1, 3)

print(arr)
print()
print(arr1)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]

[[[[ 1  5]
   [ 3  7]]

  [[ 2  6]
   [ 4  8]]]


 [[[ 9 13]
   [11 15]]

  [[10 14]
   [12 16]]]]


# 6.Demostrate the use of concetenate in array of different dimension using axes.

In [10]:
import numpy as np

arr= np.array([[1, 2],[3, 4]])

arr1 = np.array([5, 6])

a= np.concatenate((arr, arr1.reshape(1, -1)), axis=0)

b = np.concatenate((arr, arr1.reshape(-1, 1)), axis=1)

print("Original 2D array:")
print(arr)

print("\nOriginal 1D array:")
print(arr1)

print("\nConcatenated in rows:")
print(a)

print("\nConcatenated in columns:")
print(b)

Original 2D array:
[[1 2]
 [3 4]]

Original 1D array:
[5 6]

Concatenated in rows:
[[1 2]
 [3 4]
 [5 6]]

Concatenated in columns:
[[1 2 5]
 [3 4 6]]


# 7. Demonstrate the use of stack using an example.

In [9]:
import numpy as np
subject1 = np.array([75, 80, 85, 90])
subject2 = np.array([70, 85, 75, 95])
subject3 = np.array([80, 75, 85, 90])

stacked_array = np.stack((subject1, subject2, subject3), axis=1)

print()
print(stacked_array)


[[75 70 80]
 [80 85 75]
 [85 75 85]
 [90 95 90]]
