# 1.Create a 3D array of size (3x4)X2 means 2 two dimension array each of 3X4 and it must have element from 1 to 24 fetch  the following using index (a)=17,(b)=3,(c)=19,(d)=24. 

In [13]:
import numpy as np
arr = np.arange(1,25).reshape(2, 3, 4)


a = arr[1,1,0]  
b = arr[0,0,2]
c = arr[1,1,2]
d = arr[1,2,3]

print(arr)
print(a)
print(b)
print(c)
print(d)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
17
3
19
24


# 2.Create a 3D array of size (3x4)X2 means 2 two dimension array each of 3X4 and it must have element from 1 to 24 fetch  the following using slicing (a)=5,6,7,(b)=9,19,(c)=21,22.

In [60]:
import numpy as np
arr = np.arange(1,25).reshape(2, 3, 4)
a = arr[0,1,0:3]  
b = arr[0,2,0:1]  
c = arr[1,1,2:3] 
d =arr[1,2,0:2]
print(arr)

print(a)
print(b)
print(c)
print(d)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
[5 6 7]
[9]
[19]
[21 22]


# 3.Create a 1D array of table of 5 and fetch all the element which are divisible by 4 using advance indexing.

In [63]:
import numpy as np
arr = np.arange(1, 21) * 5
arr1=arr[arr % 4 == 0]
print(arr)
print(arr1)

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]
[ 20  40  60  80 100]


# 4.Create 2D array from number 1-12 and fetch using advance indexing.(a)=12,(b)=7,(c)=3,(d)=9.

In [2]:
import numpy as np
arr = np.arange(1, 13).reshape(3, 4)

a = arr[2, 3]  
b = arr[1, 2] 
c = arr[0, 2]  
d = arr[2, 0]  

print(arr)

print(a)
print(b)
print(c)
print(d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12
7
3
9
