# 1.Create an array of random integer from 30 to 40 .it must be a 2D arrayof size 3x4.

In [2]:
import numpy as np
arr=np.random.randint(30,40,(3,4))
print(arr)

[[37 37 33 37]
 [39 33 36 35]
 [31 30 37 31]]


# 2.Write  the code to get randomm number fromm 1 to 6 and their probbility must be unifrom distributed, also it must be an array of size 2x4.

In [17]:
import numpy as np
arr = np.random.uniform(1, 7, (2, 4))
print(arr)

[[5.79321382 2.59041402 4.31295452 4.62208003]
 [3.81589406 4.13742696 3.96267462 3.82574049]]


# 3. Write a code to get random number close to 5 with varance 2, and get 50 random number.

In [18]:
import numpy as np
num = np.random.normal(5,2,50)
print(num)

[6.66612146 3.02897743 4.8824762  1.45256388 2.58616318 5.58181695
 5.67666078 6.35457492 6.30220419 7.24643063 5.97006759 5.3979125
 5.42579682 5.65374787 3.96049546 6.29434624 7.62615521 3.96275104
 8.20288441 6.07930139 5.54702877 6.79713014 4.39208388 6.29531435
 5.58290015 3.78456891 6.43126358 6.71844498 5.16750719 3.07666993
 6.09784523 6.66376179 4.53654888 7.71978132 7.2135922  3.9136075
 3.72623722 4.30376234 6.84155114 4.50461758 3.14173826 4.21103609
 1.75149724 7.08485877 4.7854204  6.39807676 4.85917803 3.55798345
 4.55637299 1.96371857]


# 4.Create a 3D array of random number from(0 to 10).

In [19]:
import numpy as np
arr = np.random.randint(0, 11,(3, 4, 5))
print(arr)

[[[ 0  4  4  0  3]
  [10  9  8  5  3]
  [ 1  9 10  0  1]
  [ 3  7  8  8  8]]

 [[ 3  8  8  4  1]
  [ 4 10  3 10  0]
  [ 2  1 10  9  1]
  [ 8  7  2  6  1]]

 [[ 1  0  8  1  6]
  [ 4  6  1  5  3]
  [ 7  4  2  1  2]
  [ 8  4  8  4  0]]]


# 5.Make an array of table of 10 using arange function and shuffle it.

In [20]:
import numpy as np
table_of_10 = np.arange(1, 11) * 10

print("Table of 10 before shuffling:")
print(table_of_10)

np.random.shuffle(table_of_10)

print("\nTable of 10 after shuffling:")
print(table_of_10)

Table of 10 before shuffling:
[ 10  20  30  40  50  60  70  80  90 100]

Table of 10 after shuffling:
[100  60  70  90  20  10  40  80  30  50]


# 6. Create a 2D array and find its dimension, shape,size,datatype,and itemsize.

In [21]:
import numpy as np
arr= np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

dimension = arr.ndim

shape = arr.shape

size = arr.size

dtype = arr.dtype

itemsize = arr.itemsize

print("Dimension:", dimension)
print("Shape:", shape)
print("Size:", size)
print("Data type:", dtype)
print("Item size:", itemsize)

Dimension: 2
Shape: (3, 3)
Size: 9
Data type: int32
Item size: 4


# 7. Write a code to demostrate the difference between view and copy.

In [24]:
import numpy as np
org_arr = np.array([[1, 2, 3],[4, 5, 6]])

view_arr = org_arr.view()

copy_arr= org_arr.copy()

org_arr[0, 0] = 100

print("Original array:")
print(org_arr)

print("\nView array:")
print(view_arr)

print("\nCopy array:")
print(copy_arr)

Original array:
[[100   2   3]
 [  4   5   6]]

View array:
[[100   2   3]
 [  4   5   6]]

Copy array:
[[1 2 3]
 [4 5 6]]


# 8.Create this 2D array and fetch 59 out of this [[10,20,30,40,],[7,8,9,10],[10,50,60,6]].

In [25]:
import numpy as np
arr= np.array([[10, 20, 30, 40],[7, 8, 9, 10],[10, 50, 60, 6]])
value = arr[2, 1]
print("Answer:", value)

Answer: 50
